### ISSUE TITLE
SEO/advertisement

### ISSUE THREAD

**Issue by whitphx** [whitphx/vscode-emacs-mcx#1123]
This extension is not showed up at high rank in the search page regardless of the high review score.
Ref: https://www.buymeacoffee.com/whitphx/c/2228791

**Comment by dandavison** [comment]
I'm not sure if the name matters, but I find the word "Keymap" a bit strange, since the extension does much more than just mapping keys. Perhaps it should just be

```
Emacs
Emacs emulation for VSCode
```

Like

<img width="661" alt="image" src="https://user-images.githubusercontent.com/52205/194732572-031b23b7-c424-4d90-ace3-df4eb59557b6.png">

**Comment by whitphx** [comment]
Thank you! but we can only choose the predefined values for the `categories` field: `[Programming Languages, Snippets, Linters, Themes, Debuggers, Formatters, Keymaps, SCM Providers, Other, Extension Packs, Language Packs, Data Science, Machine Learning, Visualization, Notebooks, Education, Testing]`
Ref: https://code.visualstudio.com/api/references/extension-manifest#fields

**Comment by whitphx** [comment]
Sorry I totally misunderstood what you wrote.
Will take it, thanks!

**Comment by dandavison** [comment]
Great! Personally, I would also consider changing the `displayName` to something simple like "Emacs" or "Emacs Mode". Your extension is the best Emacs emulation in VSCode as far as I know, so there is no reason for the other ones to be called "Emacs"! Calling it a "Keymap" makes it sound to me like it "only maps keys" and somehow the other ones called Emacs will do more. Also personally I'm not a fan of the word "Awesome" in the name. It can come across as non-serious and non-professional, whereas your extension is a very serious piece of work that can absolutely be used professionally (and is!).


<img width="559" alt="image" src="https://github.com/whitphx/vscode-emacs-mcx/assets/52205/0799fd83-0495-407a-9717-05e6e888f940">

**Comment by dandavison** [comment]
@whitphx could I ask you to take a look at my comment above? https://github.com/whitphx/vscode-emacs-mcx/issues/1123#issuecomment-2117404156

Your emacs extension is the best as far as I know -- how about simply calling it "Emacs" or "Emacs Mode"?

"Awesome Emacs Keymap" isn't a good name in my opinion, because "Awesome" sounds non-serious, and "Keymap" makes it sound like something obscure and technical. I'm bringing this up because I'd like to attract users and contributors to your project.
