### ISSUE TITLE
Ctrl-S doesn't seem to work at all

### ISSUE THREAD

**Issue by dbikel** [whitphx/vscode-emacs-mcx#1322]
C-s seemed to be bound initially to both the Find Next action as well as emacs-mcx.isearchForward.  However, this sort of worked, in that hitting C-s would bring up the native VSCode "Find" overlay in the upper right-hand corner, but the focus would not be on it, so it would require a mouse click to enter a search string.  Subsequent hitting C-s would then search for that string.

This is quite different from true emacs-style incremental search, in which one hits C-s then immediately starts typing characters, and the search string is found (or not) as typing happens, with subsequent C-s resulting in finding subsequent instances of the current search string, if any.

Is true emacs-like increment search (both forward and backward) in the works?  Or is there a particular trick to enabling it?  I tried removing the the C-s keybinding from "Find Next", but this resulted in nothing happening when hitting C-s.

Note that none of the above is related to the editor.find.seedSearchStringFromSelection setting (which I disabled).

**Comment by whitphx** [comment]
> hitting C-s would bring up the native VSCode "Find" overlay in the upper right-hand corner, but the focus would not be on it

That's weird. It does not happen in my env (macOS, VSCode 1.67.2 (Universal)) and the find widget gets focused with the first C-s hitting.

* Please describe your environment, e.g. OS, VSCode version, or any other special configs if exist
* Please try the lower versions of this extension than v0.41.0. Since then, the implementation of C-s has been changed.
  * Ref: #1278

**Comment by dbikel** [comment]
Can you please also comment on whether the default keymap assigns Ctrl-S to
*both* the native Find command *and* the extensions' isearchForward command?

Thanks,
Dan.

**Comment by whitphx** [comment]
Thanks, so it's because you are using an older version of VSCode.
Please see https://github.com/whitphx/vscode-emacs-mcx/issues/1279#issuecomment-1113133740

As the versions of this extension between v0.41.0 and v0.42.0 have invalid version compatibility metadata and cause confusion like yours, I wanted to unpublish these versions, but could not: https://github.com/microsoft/vsmarketplace/issues/235

**Comment by dbikel** [comment]
Oh, that makes sense!  Thanks for the update.  I'll work on getting my
company to provide a more recent version of VSCode.

Thanks also for making this VSCode extension!  I sent in a donation to show
my appreciation. :)

--Dan.
