### ISSUE TITLE
apparent regression in tab behavior (with Python, at least)

### ISSUE THREAD

**Issue by jelson** [whitphx/vscode-emacs-mcx#1898]
A recent release seems to have broken Tab in "strict emacs mode".

Previously, in strict emacs mode while editing Python, pressing tab repeatedly on a blank line would cycle the cursor positoin through all the syntactically valid columns. Now it seems to be stuck on column 1, pressing tab has no effect, and I have to keep hitting space to get to the column I want.

Thank you for the extension! (I bought you a coffee :) )

**Comment by jelson** [comment]
I tried prior versions and found the break happened in the upgrade from 50.4 to 51.0.

**Comment by whitphx** [comment]
Thank you for the report and support :)

Looks like it's due to [`emacs-mcx.emacsLikeTab`](https://github.com/whitphx/vscode-emacs-mcx?tab=readme-ov-file#emacs-mcxemacsliketab) but not `emacs-mcx.strictEmacsMove`. It was introduced in 0.51.0 as you wrote.
Please disable this behavior by setting `emacs-mcx.emacsLikeTab` as `false` for now as you can do it keeping `emacs-mcx.strictEmacsMove` as `true`.

I'm trying to find a way to improve the tab behavior in Python itself.

**Comment by whitphx** [comment]
Should be fixed with v0.60.0.
Plz let me know and reopen this issue if there is still a problem.

**Comment by jelson** [comment]
Works great now! Thank you so much - I will buy you another coffee!

**Comment by whitphx** [comment]
Thank you!
