### ISSUE TITLE
Exit of C-s

### ISSUE THREAD

**Issue by pasha-bolokhov** [whitphx/vscode-emacs-mcx#277]
The interactive search in Emacs, invoked by C-s, is normally exited via:
[Enter] → to stop at the currently found instance of the search word
[C-g]    → to "quit", and return to the position where the cursor was before the search

Same with the reverse search C-r

Could these be implemented? The current implementation is confusingly very different
If I grow smart enough, I may be able to do these things myself
Thanks!

**Comment by tuttieee** [comment]
> [Enter] → to stop at the currently found instance of the search word

To simulate this behavior, I simply assigned Enter key to close the find widget in #350 . It will be available in the next release.

> [C-g] → to "quit", and return to the position where the cursor was before the search

but this behavior is difficult to implement because VSCode is not providing API to go back to the previous position during search.
I will remain this issue open and work on it later separately.

**Comment by whitphx** [comment]
Implemented in #666 and available on v0.27.0
