### ISSUE TITLE
window-jump equivalent (for C-x 0,1,2,o, followed by a cursor jump)

### ISSUE THREAD

**Issue by brianmingus2** [whitphx/vscode-emacs-mcx#628]
In emacs, I have the following config to facilitate navigating through tiled windows, which this extensions supports creating in vscode:

```
(use-package window-jump
             :bind (("M-i" . window-jump-up)
                    ("M-k" . window-jump-down)
                    ("M-j" . window-jump-left)
                    ("M-l" . window-jump-right)))
```

With this extension in vs-code we can use C-x-o to cycle around them, but we can't quickly jump as emacs allows.

**Comment by whitphx** [comment]
VSCode has `workbench.action.navigate{Up,Down,Right,Left}` commands to do such navigations, which you can set on your own `keybindings.json`. See https://stackoverflow.com/questions/33271488/shortcut-key-for-switching-between-split-panes/33276179

I do not have a plan to implement them into this extension since these commands are not provided on Emacs by default.
